name: Build

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set release date
      run: |
        echo "tag=$(date +'%Y%m%d%H%M%S')" >> ${GITHUB_ENV}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build
      run: DOCKER_TAG=shawnlu/consul2istio:${{ env.tag }} make docker-build
 
    -
      name: Push
      run: DOCKER_TAG=shawnlu/consul2istio:${{ env.tag }} make docker-push
